package mcputil

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/bhaskarjha-dev/vivechak/internal/core"
	store "github.com/bhaskarjha-dev/vivechak/internal/store"
	sdkmcp "github.com/modelcontextprotocol/go-sdk/mcp"
)

// SavePlanInput holds the arguments for vivechak_save_plan.
type SavePlanInput struct {
	ProjectRoot string `json:"project_root,omitempty" jsonschema:"workspace root path"`
	Scope       string `json:"scope,omitempty"         jsonschema:"research scope: project | decision | comparison"`
	Content     string `json:"content"                 jsonschema:"the generated plan content (Markdown)"`
	DecisionID  string `json:"decision_id,omitempty"   jsonschema:"decision identifier for decision/comparison scope (e.g. D-015)"`
	Slug        string `json:"slug,omitempty"           jsonschema:"URL-safe slug for the decision (e.g. database-selection)"`
}

func registerSavePlan(server *sdkmcp.Server) {
	sdkmcp.AddTool(server,
		&sdkmcp.Tool{
			Name:  "vivechak_save_plan",
			Title: "Save Research Plan",
			Description: "Validate and persist an agent-generated research plan. " +
				"At project scope: validates DAG structure and saves RESEARCH-PIPELINE.md + DECISIONS.md. " +
				"At decision scope: validates routing and saves [ID]-PLAN.md + proposed ADR. " +
				"At comparison scope: saves the generated comparison prompt. " +
				"Runs L1-L2 validation before saving — blocks on structural errors, warns on quality issues.",
			Annotations: &sdkmcp.ToolAnnotations{
				ReadOnlyHint:    false,
				IdempotentHint:  true,
				DestructiveHint: BoolPtr(false),
				OpenWorldHint:   BoolPtr(false),
			},
		},
		handleSavePlan,
	)
}

func handleSavePlan(_ context.Context, _ *sdkmcp.CallToolRequest, in SavePlanInput) (*sdkmcp.CallToolResult, Envelope, error) {
	const tool = "vivechak_save_plan"

	// Resolve workspace
	root, err := core.ResolveWorkspace(in.ProjectRoot)
	if err != nil {
		return ErrorResult(tool, err,
			"Initialize a workspace first with vivechak_init, or provide project_root explicitly.")
	}

	// Parse scope
	scope := core.ScopeProject
	if in.Scope != "" {
		s, ok := core.ScopeFromString(in.Scope)
		if !ok {
			return ErrorResult(tool, fmt.Errorf("invalid scope %q", in.Scope),
				"Use scope 'project', 'decision', or 'comparison'.")
		}
		scope = s
	}

	// Validate content
	if strings.TrimSpace(in.Content) == "" {
		return ErrorResult(tool, fmt.Errorf("content is required"),
			"Provide the plan content generated by the generator prompt.")
	}

	if err := validateContentSize(in.Content); err != nil {
		return ErrorResult(tool, err, "Reduce content size or split into multiple artifacts.")
	}

	if in.DecisionID != "" && !isValidID(in.DecisionID) {
		return ErrorResult(tool, fmt.Errorf("invalid decision_id %q — must be alphanumeric with optional hyphens, underscores, dots", in.DecisionID),
			"Use a simple ID like 'D-01'.")
	}
	if in.Slug != "" && !isValidID(in.Slug) {
		return ErrorResult(tool, fmt.Errorf("invalid slug %q — must be alphanumeric with optional hyphens, underscores, dots", in.Slug),
			"Use a simple slug like 'database-selection'.")
	}

	// Ensure workspace exists
	if !core.WorkspaceExists(root) {
		return ErrorResult(tool, fmt.Errorf("workspace not initialized at %s", root),
			"Run vivechak_init first to create the workspace structure.")
	}

	ws, err := store.OpenWorkspace(root)
	if err != nil {
		return ErrorResult(tool, fmt.Errorf("opening workspace: %w", err), "Provide a valid workspace.")
	}
	defer ws.Close()

	var savedFiles []string
	var warnings []string

	switch scope {
	case core.ScopeProject:
		// Validate DAG structure and cycle detection
		dag, dagErr := core.ParsePipeline([]byte(in.Content))
		if dagErr != nil {
			return ErrorResult(tool, fmt.Errorf("parsing pipeline DAG: %w", dagErr),
				"Ensure RESEARCH-PIPELINE.md contains valid session definitions.")
		}
		if valErr := dag.ValidateDAG(); valErr != nil {
			return ErrorResult(tool, fmt.Errorf("invalid pipeline DAG: %w", valErr),
				"Fix dependency cycles or dangling session references in the pipeline.")
		}

		// Save RESEARCH-PIPELINE.md
		relPath := core.PipelineFile
		unlock, err := store.LockFile(filepath.Join(root, relPath), 5*time.Second)
		if err != nil {
			return ErrorResult(tool, fmt.Errorf("could not acquire lock: %w", err), "Another process may be writing. Try again.")
		}
		defer unlock()

		if err := store.WriteFileAtomic(ws.Root(), relPath, []byte(in.Content), 0o644); err != nil {
			return ErrorResult(tool, fmt.Errorf("writing pipeline: %w", err),
				"Check filesystem permissions.")
		}
		savedFiles = append(savedFiles, relPath)

		// Ensure DECISIONS.md exists
		decPath := core.DecisionsFile
		if _, err := os.Stat(filepath.Join(root, decPath)); os.IsNotExist(err) {
			initialDecisions := []byte("# Architectural Decision Log\n\n| Decision | Title | Door Type | Status | Date |\n|---|---|---|---|---|\n")
			if err := store.WriteFileAtomic(ws.Root(), decPath, initialDecisions, 0o644); err == nil {
				savedFiles = append(savedFiles, decPath)
			}
		}

	case core.ScopeDecision:
		if in.DecisionID == "" {
			return ErrorResult(tool, fmt.Errorf("decision_id is required for decision scope"),
				"Provide a decision_id like 'D-015'.")
		}
		slug := in.Slug
		if slug == "" {
			slug = "plan"
		}
		filename := fmt.Sprintf("%s-%s.md", in.DecisionID, slug)
		relPath := filepath.Join(core.ResearchDir, filename)
		unlock, err := store.LockFile(filepath.Join(root, relPath), 5*time.Second)
		if err != nil {
			return ErrorResult(tool, fmt.Errorf("could not acquire lock: %w", err), "Another process may be writing. Try again.")
		}
		defer unlock()

		if err := store.WriteFileAtomic(ws.Root(), relPath, []byte(in.Content), 0o644); err != nil {
			return ErrorResult(tool, fmt.Errorf("writing decision plan: %w", err),
				"Check filesystem permissions.")
		}
		savedFiles = append(savedFiles, relPath)

	case core.ScopeComparison:
		if in.DecisionID == "" {
			return ErrorResult(tool, fmt.Errorf("decision_id is required for comparison scope"),
				"Provide a decision_id or comparison_id.")
		}
		filename := fmt.Sprintf("%s-comparison.md", in.DecisionID)
		relPath := filepath.Join(core.ResearchDir, filename)
		unlock, err := store.LockFile(filepath.Join(root, relPath), 5*time.Second)
		if err != nil {
			return ErrorResult(tool, fmt.Errorf("could not acquire lock: %w", err), "Another process may be writing. Try again.")
		}
		defer unlock()

		if err := store.WriteFileAtomic(ws.Root(), relPath, []byte(in.Content), 0o644); err != nil {
			return ErrorResult(tool, fmt.Errorf("writing comparison plan: %w", err),
				"Check filesystem permissions.")
		}
		savedFiles = append(savedFiles, relPath)
	}

	env := Envelope{
		Success: true,
		Message: fmt.Sprintf("Saved %s plan (%d files) at %s", scope, len(savedFiles), root),
		Data: map[string]any{
			"workspace_root": root,
			"scope":          scope,
			"saved_files":    savedFiles,
		},
		Warnings: warnings,
		NextStep: fmt.Sprintf("Run vivechak_next_session to get the first research session prompt. "+
			"Execute it in a fresh AI session with web search, then save the output with vivechak_save_session."),
		Meta: NewMeta(tool),
	}
	return env.ToResult()
}
