package mcputil

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/bhaskarjha-dev/vivechak/internal/core"
	store "github.com/bhaskarjha-dev/vivechak/internal/store"
	sdkmcp "github.com/modelcontextprotocol/go-sdk/mcp"
)

// SavePlanInput holds the arguments for vivechak_save_plan.
type SavePlanInput struct {
	ProjectRoot      string `json:"project_root,omitempty"       jsonschema:"workspace root path"`
	Scope            string `json:"scope,omitempty"              jsonschema:"research scope: project | decision | comparison"`
	Content          string `json:"content"                      jsonschema:"the generated plan content (Markdown)"`
	DecisionsContent string `json:"decisions_content,omitempty" jsonschema:"the generated initial decision registry or ADR content"`
	DecisionID       string `json:"decision_id,omitempty"        jsonschema:"decision identifier for decision/comparison scope (e.g. D-015)"`
	Slug             string `json:"slug,omitempty"               jsonschema:"URL-safe slug for the decision (e.g. database-selection)"`
}

func registerSavePlan(server *sdkmcp.Server) {
	sdkmcp.AddTool(server,
		&sdkmcp.Tool{
			Name:  "vivechak_save_plan",
			Title: "Save Research Plan",
			Description: "Validate and persist an agent-generated research plan. " +
				"At project scope: validates DAG structure and saves RESEARCH-PIPELINE.md + DECISIONS.md. " +
				"At decision scope: validates routing and saves [ID]-PLAN.md + proposed ADR. " +
				"At comparison scope: saves the generated comparison prompt. " +
				"Runs L1-L2 validation before saving — blocks on structural errors, warns on quality issues.",
			Annotations: &sdkmcp.ToolAnnotations{
				ReadOnlyHint:    false,
				IdempotentHint:  true,
				DestructiveHint: BoolPtr(false),
				OpenWorldHint:   BoolPtr(false),
			},
		},
		handleSavePlan,
	)
}

func handleSavePlan(ctx context.Context, _ *sdkmcp.CallToolRequest, in SavePlanInput) (*sdkmcp.CallToolResult, Envelope, error) {
	const tool = "vivechak_save_plan"

	// Resolve workspace
	root, err := core.ResolveWorkspace(in.ProjectRoot)
	if err != nil {
		return ErrorResult(tool, err,
			"Initialize a workspace first with vivechak_init, or provide project_root explicitly.")
	}

	// Parse scope
	scope := core.ScopeProject
	if in.Scope != "" {
		s, ok := core.ScopeFromString(in.Scope)
		if !ok {
			return ErrorResult(tool, fmt.Errorf("invalid scope %q", in.Scope),
				"Use scope 'project', 'decision', or 'comparison'.")
		}
		scope = s
	} else if core.WorkspaceExists(root) {
		info := core.InspectWorkspace(root)
		if info.Scope != "" {
			scope = info.Scope
		}
	}

	// Validate content
	if strings.TrimSpace(in.Content) == "" {
		return ErrorResult(tool, fmt.Errorf("content is required"),
			"Provide the plan content generated by the generator prompt.")
	}

	if err := validateContentSize(in.Content); err != nil {
		return ErrorResult(tool, err, "Reduce content size or split into multiple artifacts.")
	}

	if in.DecisionID != "" && !isValidID(in.DecisionID) {
		return ErrorResult(tool, fmt.Errorf("invalid decision_id %q — must be alphanumeric with optional hyphens, underscores, dots", in.DecisionID),
			"Use a simple ID like 'D-01'.")
	}
	if in.Slug != "" && !isValidID(in.Slug) {
		return ErrorResult(tool, fmt.Errorf("invalid slug %q — must be alphanumeric with optional hyphens, underscores, dots", in.Slug),
			"Use a simple slug like 'database-selection'.")
	}

	// Ensure workspace exists
	if !core.WorkspaceExists(root) {
		return ErrorResult(tool, fmt.Errorf("workspace not initialized at %s", root),
			"Run vivechak_init first to create the workspace structure.")
	}

	ws, err := store.OpenWorkspace(root)
	if err != nil {
		return ErrorResult(tool, fmt.Errorf("opening workspace: %w", err), "Provide a valid workspace.")
	}
	defer ws.Close()

	var savedFiles []string
	var warnings []string

	// L1-L2 Mechanical validation of plan content
	planValidation := core.ValidatePlan([]byte(in.Content))
	if planValidation.HasBlocking() {
		var firstErr string
		var firstHint string
		for _, issue := range planValidation.Issues {
			if issue.Level == core.L2Block {
				firstErr = issue.Message
				firstHint = issue.FixHint
				break
			}
		}
		if firstHint == "" {
			firstHint = "Fix dependency cycles, dangling session references, or missing plan content."
		}
		return ErrorResult(tool, fmt.Errorf("plan validation failed: %s", firstErr), firstHint)
	}
	for _, issue := range planValidation.Issues {
		warnings = append(warnings, issue.String())
	}

	var decValidation *core.ValidationResult
	if in.DecisionsContent != "" {
		decValidation = core.ValidateDecision([]byte(in.DecisionsContent))
		for _, issue := range decValidation.Issues {
			warnings = append(warnings, issue.String())
		}
	}

	switch scope {
	case core.ScopeProject:

		// Save RESEARCH-PIPELINE.md
		relPath := core.PipelineFile
		unlock, err := store.LockFile(ctx, filepath.Join(root, relPath), 5*time.Second)
		if err != nil {
			return ErrorResult(tool, fmt.Errorf("could not acquire lock: %w", err), "Another process may be writing. Try again.")
		}
		defer func() { _ = unlock() }()

		if err := store.WriteFileAtomic(ws.Root(), relPath, []byte(in.Content), 0o644); err != nil {
			return ErrorResult(tool, fmt.Errorf("writing pipeline: %w", err),
				"Check filesystem permissions.")
		}
		savedFiles = append(savedFiles, relPath)

		// Save DECISIONS.md (either provided DecisionsContent or default empty table)
		decPath := core.DecisionsFile
		if in.DecisionsContent != "" {
			if err := store.WriteFileAtomic(ws.Root(), decPath, []byte(in.DecisionsContent), 0o644); err == nil {
				savedFiles = append(savedFiles, decPath)
			}
		} else if _, err := ws.Stat(decPath); os.IsNotExist(err) {
			initialDecisions := []byte("# Architectural Decision Log\n\n| Decision | Title | Door Type | Status | Date |\n|---|---|---|---|---|\n")
			if err := store.WriteFileAtomic(ws.Root(), decPath, initialDecisions, 0o644); err == nil {
				savedFiles = append(savedFiles, decPath)
			}
		}

	case core.ScopeDecision:
		if in.DecisionID == "" {
			return ErrorResult(tool, fmt.Errorf("decision_id is required for decision scope"),
				"Provide a decision_id like 'D-015'.")
		}
		filename := fmt.Sprintf("%s-plan.md", in.DecisionID)
		relPath := filepath.Join(core.ResearchDir, filename)
		unlock, err := store.LockFile(ctx, filepath.Join(root, relPath), 5*time.Second)
		if err != nil {
			return ErrorResult(tool, fmt.Errorf("could not acquire lock: %w", err), "Another process may be writing. Try again.")
		}
		defer func() { _ = unlock() }()

		if err := store.WriteFileAtomic(ws.Root(), relPath, []byte(in.Content), 0o644); err != nil {
			return ErrorResult(tool, fmt.Errorf("writing decision plan: %w", err),
				"Check filesystem permissions.")
		}
		savedFiles = append(savedFiles, relPath)

		if in.DecisionsContent != "" {
			adrSlug := in.Slug
			if adrSlug == "" {
				adrSlug = "decision"
			}
			adrFilename := fmt.Sprintf("%s-%s.md", in.DecisionID, adrSlug)
			adrRelPath := filepath.Join(core.ResearchDir, adrFilename)
			if err := store.WriteFileAtomic(ws.Root(), adrRelPath, []byte(in.DecisionsContent), 0o644); err != nil {
				return ErrorResult(tool, fmt.Errorf("writing proposed ADR %s: %w", adrFilename, err),
					"Check filesystem permissions.")
			}
			savedFiles = append(savedFiles, adrRelPath)
		}

	case core.ScopeComparison:
		if in.DecisionID == "" {
			return ErrorResult(tool, fmt.Errorf("decision_id is required for comparison scope"),
				"Provide a decision_id or comparison_id.")
		}
		filename := fmt.Sprintf("%s-comparison.md", in.DecisionID)
		if in.Slug != "" {
			filename = fmt.Sprintf("%s-cmp-%s.md", in.DecisionID, in.Slug)
		}
		relPath := filepath.Join(core.ResearchDir, filename)
		unlock, err := store.LockFile(ctx, filepath.Join(root, relPath), 5*time.Second)
		if err != nil {
			return ErrorResult(tool, fmt.Errorf("could not acquire lock: %w", err), "Another process may be writing. Try again.")
		}
		defer func() { _ = unlock() }()

		if err := store.WriteFileAtomic(ws.Root(), relPath, []byte(in.Content), 0o644); err != nil {
			return ErrorResult(tool, fmt.Errorf("writing comparison plan: %w", err),
				"Check filesystem permissions.")
		}
		savedFiles = append(savedFiles, relPath)
	}

	dataMap := map[string]any{
		"workspace_root": root,
		"scope":          scope,
		"saved_files":    savedFiles,
		"validation":     planValidation,
	}
	if decValidation != nil {
		dataMap["decisions_validation"] = decValidation
	}

	env := Envelope{
		Success: true,
		Message: fmt.Sprintf("Saved %s plan (%d files) at %s", scope, len(savedFiles), root),
		Data:    dataMap,
		Warnings: warnings,
		NextStep: fmt.Sprintf("Run vivechak_next_session to get the first research session prompt. "+
			"Execute it in a fresh AI session with web search, then save the output with vivechak_save_session."),
		Meta: NewMeta(tool),
	}
	return env.ToResult()
}
